init_pose: [0.0, -0.5, 0.4, 1, 0, 0, 0] #x y z qx qy qz qw

controller:
  cartesian_stiffness: [200,200,200,10,10,10]
  cartesian_damping: [0.5,0.5,0.5,0.2,0.2,0.2]
  nullspace_stiffness: 10
  nullspace_damping: 0.5

scan:
  marching_vel: 0.5
