init_pose: [0.6, 0.1, 0, 0, 1, 0, 0] #x y z qx qy qz qw

controller:
  cartesian_stiffness: [20,20,20,20,20,20]
  cartesian_damping: [0.2,0.2,0.2,0.2,0.2,0.2]
  nullspace_stiffness: 10
  nullspace_damping: 0.2

scan:
  marching_vel: 0.01